apiVersion: v1
kind: Service
metadata:
  name: fromk8s
spec:
  selector:
    app: fromk8s
  ports:
  - name: web
    nodePort: 30084
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
